sudo: required
services:
  - docker

before_install:
  - docker build -t mgh1990/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true mgh1990/react-test npm test

after_success:
  - docker build -t mgh1990/multi-client ./client
  - docker build -t mgh1990/multi-nginx ./nginx
  - docker build -t mgh1990/multi-server ./server
  - docker build -t mgh1990/multi-worker ./worker


